version: '3.8'
services:
  nodeAlpine:
    container_name: bedybot-api
    build:
      context: .
      target: nodeAlpine
    ports:
      - 8081:3000
    image: bedybot-api:latest
    volumes:
      # - .:/usr/src/app
      - type: bind
        source: E:/database
        target: /usr/src/db

  mailhog:
    container_name: mailhog-api
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  database:

  # nginx:
  #   container_name: bedybot-frontEnd
  #   build:
  #     context: .
  #     target: nginx
  #   ports:
  #     - 8080:80
  #   image: bedybot-frontend:latest
  #   volumes:
  #     - ../WebSite:/usr/src/app

