version: '3.8'
services:
  nodeAlpine:
    container_name: bedyboy-apiServer
    build:
      context: .
      target: nodeAlpine
    ports:
      - 8081:3000
    image: bedybot-apiserver:latest
    volumes:
      - ./dist/website:/usr/share/nginx/html
  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025

