version: '3.8'
services:
  nodeApi:
    container_name: bedybot-api
    build:
      context: .
      target: nodeBedyApi
    ports:
      - 8081:3000
    image: bedybot-api:latest
    volumes:
      - e:/database:/usr/db

  mailhog:
    container_name: mailhog-api
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025